name: sim
channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch=2.2.2
  - torchvision=0.17.2
  - torchaudio=2.2.2
  - pytorch-cuda=12.1

  - pip:
      - https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.2cxx11abiFALSE-cp310-cp310-linux_x86_64.whl  # FlashAttention 2 (CUDA 12.1, PyTorch 2.2)
      - numpy==1.26.4
      - accelerate==0.29.2
      - deepspeed==0.12.2
      - transformers==4.44.2
      - trl==0.9.6
      - huggingface-hub==0.23.2
      - datasets==2.18.0
      - peft==0.7.1
