name: ae
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - alpaca-eval==0.6.2
      - vllm==0.8.4
      - transformers==4.51.3
      - datasets==3.5.0
      - https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
